def heroEntity(item) -> dict:
    return {
        "id": item.get("id"),
        "name": item.get("name"),
        "Gender": item.get("Gender"),
        "Eye color": item.get("Eye color"),
        "Race": item.get("Race"),
        "Hair color": item.get("Hair color"),
        "Height": item.get("Height"),
        "Publisher": item.get("Publisher"),
        "Skin color": item.get("Skin color"),
        "Alignment": item.get("Alignment"),
        "Weight": item.get("Weight"),
        "hero_names": item.get("hero_names"),
        "Agility": item.get("Agility"),
        "Accelerated Healing": item.get("Accelerated Healing"),
        "Lantern Power Ring": item.get("Lantern Power Ring"),
        "Dimensional Awareness": item.get("Dimensional Awareness"),
        "Cold Resistance": item.get("Cold Resistance"),
        "Durability": item.get("Durability"),
        "Stealth": item.get("Stealth"),
        "Energy Absorption": item.get("Energy Absorption"),
        "Flight": item.get("Flight"),
        "Danger Sense": item.get("Danger Sense"),
        "Underwater breathing": item.get("Underwater breathing"),
        "Marksmanship": item.get("Marksmanship"),
        "Weapons Master": item.get("Weapons Master"),
        "Power Augmentation": item.get("Power Augmentation"),
        "Animal Attributes": item.get("Animal Attributes"),
        "Longevity": item.get("Longevity"),
        "Intelligence": item.get("Intelligence"),
        "Super Strength": item.get("Super Strength"),
        "Cryokinesis": item.get("Cryokinesis"),
        "Telepathy": item.get("Telepathy"),
        "Energy Armor": item.get("Energy Armor"),
        "Energy Blasts": item.get("Energy Blasts"),
        "Duplication": item.get("Duplication"),
        "Size Changing": item.get("Size Changing"),
        "Density Control": item.get("Density Control"),
        "Stamina": item.get("Stamina"),
        "Astral Travel": item.get("Astral Travel"),
        "Audio Control": item.get("Audio Control"),
        "Dexterity": item.get("Dexterity"),
        "Omnitrix": item.get("Omnitrix"),
        "Super Speed": item.get("Super Speed"),
        "Possession": item.get("Possession"),
        "Animal Oriented Powers": item.get("Animal Oriented Powers"),
        "Weapon-based Powers": item.get("Weapon-based Powers"),
        "Electrokinesis": item.get("Electrokinesis"),
        "Darkforce Manipulation": item.get("Darkforce Manipulation"),
        "Death Touch": item.get("Death Touch"),
        "Teleportation": item.get("Teleportation"),
        "Enhanced Senses": item.get("Enhanced Senses"),
        "Telekinesis": item.get("Telekinesis"),
        "Energy Beams": item.get("Energy Beams"),
        "Magic": item.get("Magic"),
        "Hyperkinesis": item.get("Hyperkinesis"),
        "Jump": item.get("Jump"),
        "Clairvoyance": item.get("Clairvoyance"),
        "Dimensional Travel": item.get("Dimensional Travel"),
        "Power Sense": item.get("Power Sense"),
        "Shapeshifting": item.get("Shapeshifting"),
        "Peak Human Condition": item.get("Peak Human Condition"),
        "Immortality": item.get("Immortality"),
        "Camouflage": item.get("Camouflage"),
        "Element Control": item.get("Element Control"),
        "Phasing": item.get("Phasing"),
        "Astral Projection": item.get("Astral Projection"),
        "Electrical Transport": item.get("Electrical Transport"),
        "Fire Control": item.get("Fire Control"),
        "Projection": item.get("Projection"),
        "Summoning": item.get("Summoning"),
        "Enhanced Memory": item.get("Enhanced Memory"),
        "Reflexes": item.get("Reflexes"),
        "Invulnerability": item.get("Invulnerability"),
        "Energy Constructs": item.get("Energy Constructs"),
        "Force Fields": item.get("Force Fields"),
        "Self-Sustenance": item.get("Self-Sustenance"),
        "Anti-Gravity": item.get("Anti-Gravity"),
        "Empathy": item.get("Empathy"),
        "Power Nullifier": item.get("Power Nullifier"),
        "Radiation Control": item.get("Radiation Control"),
        "Psionic Powers": item.get("Psionic Powers"),
        "Elasticity": item.get("Elasticity"),
        "Substance Secretion": item.get("Substance Secretion"),
        "Elemental Transmogrification": item.get("Elemental Transmogrification"),
        "Technopath/Cyberpath": item.get("Technopath/Cyberpath"),
        "Photographic Reflexes": item.get("Photographic Reflexes"),
        "Seismic Power": item.get("Seismic Power"),
        "Animation": item.get("Animation"),
        "Precognition": item.get("Precognition"),
        "Mind Control": item.get("Mind Control"),
        "Fire Resistance": item.get("Fire Resistance"),
        "Power Absorption": item.get("Power Absorption"),
        "Enhanced Hearing": item.get("Enhanced Hearing"),
        "Nova Force": item.get("Nova Force"),
        "Insanity": item.get("Insanity"),
        "Hypnokinesis": item.get("Hypnokinesis"),
        "Animal Control": item.get("Animal Control"),
        "Natural Armor": item.get("Natural Armor"),
        "Intangibility": item.get("Intangibility"),
        "Enhanced Sight": item.get("Enhanced Sight"),
        "Molecular Manipulation": item.get("Molecular Manipulation"),
        "Heat Generation": item.get("Heat Generation"),
        "Adaptation": item.get("Adaptation"),
        "Gliding": item.get("Gliding"),
        "Power Suit": item.get("Power Suit"),
        "Mind Blast": item.get("Mind Blast"),
        "Probability Manipulation": item.get("Probability Manipulation"),
        "Gravity Control": item.get("Gravity Control"),
        "Regeneration": item.get("Regeneration"),
        "Light Control": item.get("Light Control"),
        "Echolocation": item.get("Echolocation"),
        "Levitation": item.get("Levitation"),
        "Toxin and Disease Control": item.get("Toxin and Disease Control"),
        "Banish": item.get("Banish"),
        "Energy Manipulation": item.get("Energy Manipulation"),
        "Heat Resistance": item.get("Heat Resistance"),
        "Natural Weapons": item.get("Natural Weapons"),
        "Time Travel": item.get("Time Travel"),
        "Enhanced Smell": item.get("Enhanced Smell"),
        "Illusions": item.get("Illusionsn"),
        "Thirstokinesis": item.get("Thirstokinesis"),
        "Hair Manipulation": item.get("Hair Manipulation"),
        "Illumination": item.get("Illumination"),
        "Omnipotent": item.get("Omnipotent"),
        "Cloaking": item.get("Cloaking"),
        "Changing Armor": item.get("Changing Armor"),
        "Power Cosmic": item.get("Power Cosmic"),
        "Biokinesis": item.get("Biokinesis"),
        "Water Control": item.get("Water Control"),
        "Radiation Immunity": item.get("Radiation Immunity"),
        "Vision - Telescopic": item.get("Vision - Telescopic"),
        "Toxin and Disease Resistance": item.get("Toxin and Disease Resistance"),
        "Spatial Awareness": item.get("Spatial Awareness"),
        "Energy Resistance": item.get("Energy Resistance"),
        "Telepathy Resistance": item.get("Telepathy Resistance"),
        "Molecular Combustion": item.get("Molecular Combustion"),
        "Omnilingualism": item.get("Omnilingualism"),
        "Portal Creation": item.get("Portal Creation"),
        "Magnetism": item.get("Magnetism"),
        "Mind Control Resistance": item.get("Mind Control Resistance"),
        "Plant Control": item.get("Plant Control"),
        "Sonar": item.get("Sonar"),
        "Sonic Scream": item.get("Sonic Scream"),
        "Time Manipulation": item.get("Time Manipulation"),
        "Enhanced Touch": item.get("Enhanced Touch"),
        "Magic Resistance": item.get("Magic Resistance"),
        "Invisibility": item.get("Invisibility"),
        "Sub-Mariner": item.get("Sub-Mariner"),
        "Radiation Absorption": item.get("Radiation Absorption"),
        "Intuitive aptitude": item.get("Intuitive aptitude"),
        "Vision - Microscopic": item.get("Vision - Microscopic"),
        "Melting": item.get("Melting"),
        "Wind Control": item.get("Wind Control"),
        "Super Breath": item.get("Super Breath"),
        "Wallcrawling": item.get("Wallcrawling"),
        "Vision - Night": item.get("Vision - Night"),
        "Vision - Infrared": item.get("Vision - Infrared"),
        "Grim Reaping": item.get("Grim Reaping"),
        "Matter Absorption": item.get("Matter Absorption"),
        "The Force": item.get("The Force"),
        "Resurrection": item.get("Resurrection"),
        "Terrakinesis": item.get("Terrakinesis"),
        "Vision - Heat": item.get("Vision - Heat"),
        "Vitakinesis": item.get("Vitakinesis"),
        "Radar Sense": item.get("Radar Sense"),
        "Qwardian Power Ring": item.get("Qwardian Power Ring"),
        "Weather Control": item.get("Weather Control"),
        "Vision - X-Ray": item.get("Vision - X-Ray"),
        "Vision - Thermal": item.get("Vision - Thermal"),
        "Web Creation": item.get("Web Creation"),
        "Reality Warping": item.get("Reality Warping"),
        "Odin Force": item.get("Odin Force"),
        "Symbiote Costume": item.get("Symbiote Costume"),
        "Speed Force": item.get("Speed Force"),
        "Phoenix Force": item.get("Phoenix Force"),
        "Molecular Dissipation": item.get("Molecular Dissipation"),
        "Vision - Cryo": item.get("Vision - Cryo"),
        "Omnipresent": item.get("Omnipresent"),
        "Omniscient": item.get("Omniscient")

    }

def heroesEntity(entity) -> list:
    return [heroEntity(item) for item in entity]